version: '3.7'

services: 
  crud-service:
    build: 
      context: .
      dockerfile: NotesApp.CRUD.Service/src/NotesApp.Api/Dockerfile
    environment:
      - ConnectionStrings__DefaultConnection=Server=crud-service-db;Database=NotesApp;User=sa;Password=${SECRET_PASSWORD};MultipleActiveResultSets=true;Trusted_Connection=false;
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_Kestrel__Certificates__Default__Password=${SECRET_PASSWORD}
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
    depends_on:
      - crud-service-db
    restart: on-failure
    ports:
      - 8001:80
      - 4431:443
    volumes:
      - ~/.aspnet/https:/https:ro

  history-service:
    build: 
      context: .
      dockerfile: NotesApp.History.Service/src/NotesApp.History.Service.Api/Dockerfile
    environment:
      - ConnectionStrings__DefaultConnection=Server=history-service-db;Database=NotesApp;User=sa;Password=${SECRET_PASSWORD};MultipleActiveResultSets=true;Trusted_Connection=false;
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_Kestrel__Certificates__Default__Password=${SECRET_PASSWORD}
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
    depends_on:
      - history-service-db
    restart: on-failure
    ports:
      - 8002:80
      - 4432:443
    volumes:
      - ~/.aspnet/https:/https:ro
    
  webui-service:
    build:
      context: .
      dockerfile: NotesApp.WebUI.Service/Dockerfile
    ports: 
      - 8080:80
    depends_on: 
      - crud-service
  
  crud-service-db:
    image: mcr.microsoft.com/mssql/server
    environment: 
      - "ACCEPT_EULA=Y"
      - "SA_PASSWORD=${SECRET_PASSWORD}"

  history-service-db:
    image: mcr.microsoft.com/mssql/server
    environment: 
      - "ACCEPT_EULA=Y"
      - "SA_PASSWORD=${SECRET_PASSWORD}"