version: '3.7'

services: 
  crud-service:
    build: 
      context: .
      dockerfile: NotesApp.CRUD.Service/src/NotesApp.Api/Dockerfile
    ports:
      - 5000:5000
    depends_on:
      - db
    restart: on-failure

  history-service:
    build: 
      context: .
      dockerfile: NotesApp.History.Service/src/NotesApp.History.Service.Api/Dockerfile
    ports:
      - 5003:5003
    depends_on:
      - db
    restart: on-failure
    
  webui-service:
    build:
      context: .
      dockerfile: NotesApp.WebUI.Service/Dockerfile
    ports: 
      - 8080:80
    depends_on: 
      - crud-service
  
  db:
    image: mcr.microsoft.com/mssql/server
    environment: 
      - "ACCEPT_EULA=Y"
      - "SA_PASSWORD=My_password123"